version: 0.2
        
phases:
  install:
    on-failure: ABORT
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing Serverless Framework...
      - npm i -g serverless@2
      - cd notes
      - echo Installing dependencies...
      - npm i
    # steps:
  build:
    on-failure: ABORT
    commands:
      - echo deploying resources......
      - serverless deploy --stage dev --verbose    
    # steps
artifacts:
  files:
    - notes/my-artifact/**
  name: MyProjectArtifacts
cache:
  paths:
    - 'notes/node_modules/**/*'
#push